version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mysql
      - mongodb
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  mongo-data:
  redis-data:
